// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkTracker.Contexts;

namespace WorkTracker.Migrations
{
    [DbContext(typeof(WorkDayContext))]
    [Migration("20181202194613_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WorkTracker.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("End");

                    b.Property<DateTimeOffset?>("Start");

                    b.HasKey("Id");

                    b.ToTable("WorkDays");
                });
#pragma warning restore 612, 618
        }
    }
}
